# Welcome to Jekyll!
#

# Site settings
title: Jiehuan Sun
description: |
  Biostatistics
owner: Jiehuan Sun # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: jiehuan.sun@yale.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiehuansun.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  email: mailto:jiehuan.sun@yale.edu
  google-scholar: https://scholar.google.com/citations?user=wX1K4ogAAAAJ&hl=en
  github: https://github.com/sunnypig1988
  linkedin-square: https://linkedin.com/in/jiehuan-sun-07724339
  facebook-official: https://facebook.com/sun.jiehuan
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
